webos-compat.inc: Remove world-license from ROS_WORLD_SKIP_GROUPS
* webOS OSE depends on gstreamer1.0-plugins-bad from gstreamer1.0-omx,
  g-media-pipeline and g-camera-pipeline

  and already sets necessary license flags:
  meta-webos/conf/distro/webos.conf:LICENSE_FLAGS_WHITELIST_append = " commercial_gstreamer1.0-omx"
  and removes the restricted faad dependency:
  meta-webos-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.14.%.bbappend:PACKAGECONFIG_remove_rpi = "faad"

* fixes:
ERROR: Nothing RPROVIDES 'gstreamer1.0-plugins-bad' (but meta-webosose/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
gstreamer1.0-plugins-bad was skipped: Recipe is blacklisted: depends on faad2 which has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
gstreamer1.0-plugins-bad was skipped: Recipe is blacklisted: depends on faad2 which has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'gstreamer1.0-plugins-bad' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-bad']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'gstreamer1.0-plugins-bad']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-webos-extended', 'gstreamer1.0-plugins-bad']
ERROR: Nothing PROVIDES 'gstreamer1.0-plugins-bad' (but meta-webosose/meta-webos/recipes-multimedia/g-media-pipeline/g-media-pipeline.bb, meta-webosose/meta-webos/recipes-webos/g-camera-pipeline/g-camera-pipeline.bb, openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.14.4.bb DEPENDS on or otherwise requires it)
gstreamer1.0-plugins-bad was skipped: Recipe is blacklisted: depends on faad2 which has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
gstreamer1.0-plugins-bad was skipped: Recipe is blacklisted: depends on faad2 which has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'g-media-pipeline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['g-media-pipeline', 'gstreamer1.0-plugins-bad']
NOTE: Runtime target 'g-camera-pipeline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['g-camera-pipeline', 'gstreamer1.0-plugins-bad']
NOTE: Runtime target 'gstreamer1.0-omx' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-omx', 'gstreamer1.0-plugins-bad']
ERROR: Nothing RPROVIDES 'g-media-pipeline-dev' (but meta-webosose/meta-webos/recipes-multimedia/g-media-pipeline/g-media-pipeline.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'g-media-pipeline-dev'
NOTE: Runtime target 'g-media-pipeline-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['g-media-pipeline-dev']
ERROR: Nothing RPROVIDES 'g-camera-pipeline-dev' (but meta-webosose/meta-webos/recipes-webos/g-camera-pipeline/g-camera-pipeline.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'g-camera-pipeline-dev'
NOTE: Runtime target 'g-camera-pipeline-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['g-camera-pipeline-dev']
ERROR: Nothing RPROVIDES 'gstreamer1.0-omx-dev' (but openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.14.4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gstreamer1.0-omx-dev'
NOTE: Runtime target 'gstreamer1.0-omx-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-omx-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>